version: '3'

services:
  app:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "apt-get update && apt-get install -y ffmpeg && pip3 install -r requirements.txt && python nova.py"
    ports:
      - 7860:7860
