version: '3'

services:
    jupyter:
        image: 'jupyter/datascience-notebook:latest'
        ports:
            - '8888:8888'
        volumes:
          - ./workspace:/home/jovyan/work
        container_name: jupyter
        environment:
          JUPYTER_ENABLE_LAB: 'yes'

