version: '3'

services:
  app:
    image: python:3.9-slim
    command: python app.py
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 7000:7000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
    depends_on:
      - db

  db:
    image: postgres:13
