version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: "/sbin/tini -- /usr/local/bin/jenkins.sh"
    depends_on:
      - docker

  docker:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --storage-driver=overlay2

  dependencies:
    image: debian
    user: root
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        libnss3 \
        libxcb \
        libxcb1 \
        libxi6 \
        libgconf-2-4 \
        chromium-driver \
        software-properties-common &&
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - &&
        apt-key fingerprint 0EBFCD88 &&
        add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable\" &&
        apt-get update &&
        apt-get install -y docker-ce-cli
      "