name: Testing the Project

on:
  push:
    branches:
      - 'master' 
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build csharp
      run: |
        cd booosttag; docker-compose up -d
        cd booosttag; docker-compose down