name: Testing the Project

on:
  push:
    branches:
      - 'master' 
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: environment
      env:
        ROOT_DIRECTORY: .
      run: |
        pwd;
        cd ROOT_DIRECTORY
    - name: docker-compose BoostTag Wordpress
      run: |
        pwd;
        cd ROOT_DIRECTORY;
        cd boosttag; docker-compose up -d
        docker-compose down