name: Testing the Project

on:
  push:
    branches:
      - 'master' 
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker-compose BoostTag Wordpress
      run: |
        cd boosttag; docker-compose up -d
        cd boosttag; docker-compose down