name: Testing the Project

on:
  push:
    branches:
      - 'master' 
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: docker-compose BoostTag Wordpress
      run: |
        cd boosttag; docker-compose up -d
        docker-compose down; cd ..;
    - name: docker-compose Flask
      run: |
        cd learn/flask_compose_sample; docker-compose up -d
        docker-compose down; cd ../..;