name: Testing the Project

on:
  push:
    branches:
      - 'master' 
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: docker-compose boosttag
      run: |
        cd boosttag; docker-compose up -d
        docker-compose down; cd ..;
    - name: docker-compose machinlearning
      run: |
        docker volume create --name=db_data
        cd machinlearning; docker-compose up -d
        docker-compose down; cd ..;
    - name: docker-compose jupyterlab
      run: |
        cd jupyterlab; docker-compose up -d
        docker-compose down; cd ..;